### ISSUE TITLE
edge cases

### ISSUE THREAD

**Issue by lue-bird** [arowM/elm-multiline-string#1]
#### single-line `"""` strings currently get stripped of their indentation

```elm
here """    test    """
--> "test    "
```
not `"    test    "`.  Is this intentional?

#### The indentation of an empty line with the closing `"""` is not taken into account

```elm
here """
    test
  """
--> "test"
``` 
not `"  test"`. Is this intentional?

#### if the first line containing the opening `"""` contains non-spaces, its indentation is taken into account

```elm
here """title
    test
    """
--> " title\n    test"
```
not `"title\ntest"`. Is this intentional?

-------
If it helps, [here's a fork with a lot of documentation for the cases and behavior like what I described in "not `...`"](https://github.com/lue-bird/elm-multiline-string/blob/main/src/String/Multiline.elm)

Anyway, the idea of `elm-multiline-string` is great, thanks for making it!

**Comment by arowM** [comment]
> not "    test    ". Is this intentional?

Yes. If you want such result, just use `"""    test    """` without `here` function.

> not "  test". Is this intentional?

Yes. If you want such result, just use `"""  test"""` without `here` function.

The following cases, which are more likely to be practical, are duly considered:

```elm
here """
    with indent
  next line
  """
--> "  with indent\nnext line"
```

> not "title\ntest". Is this intentional?

Yes.
Who in the world would write that way for any practical benefit? What exactly do they want to benefit from writing like that?
This library is just for the purpose of "not breaking indentation," so there is no need to take care of those who use it for other purposes.
It would be better to prohibit such abuses with elm-review.

Thanks for your interest!
